import { Montserrat_Alternates } from 'next/font/google';
import styles from './Layout.module.scss';
import Navbar from '../Navbar/Navbar';
import Footer from '../Footer/Footer';
import cn from 'classnames';

const font = Montserrat_Alternates({
  variable: '--font-mont-alt',
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const classNames = cn(font.variable, styles.main);
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
