import './globals.css';
import { Montserrat_Alternates } from 'next/font/google';

import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';

const font = Montserrat_Alternates({ 
  weight: ['300', '400', '500', '700'], 
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
